name: Docker build and push

on:
  push:
    branches:
      - 'main'

# Ogranicava da samo jedan job moze da bude pokrenut u isto vreme
concurrency: ci-${{ github.ref }}

jobs:
  docker-build-push:
    name: Build and push latest images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build and Push bolnica-eureka image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./eureka
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/raf-si-2021/bolnica-eureka:latest

      # - name: Build and Push bolnica-gateway image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./gateway
      #     platforms: linux/amd64
      #     push: true
      #     tags: ghcr.io/raf-si-2021/bolnica-gateway:latest

      - name: Build and Push bolnica-user-service image
        uses: docker/build-push-action@v2
        with:
          context: ./user
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/bolnica-user-service:latest

      - name: Build and Push bolnica-management-service image
        uses: docker/build-push-action@v2
        with:
          context: ./management
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/bolnica-management-service:latest

      - name: Build and Push bolnica-laboratory-service image
        uses: docker/build-push-action@v2
        with:
          context: ./laboratory
          platforms: linux/amd64
          push: true
          tags: ghcr.io/raf-si-2021/bolnica-laboratory-service:latest